baseURL = "https://christian-middle-earth.me/"
languageCode = "en-us"
title = "Genesis 1-11: A Commentary for Christian Middle-earth"
theme = "PaperMod"

[params]
  description = "A commentary on Genesis 1-11 for Christian Middle-earthers by Christian Middle-earthers"
  ShowReadingTime = true
  ShowShareButtons = false
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = false
  ShowToc = true
  TocOpen = falsepanel-1-35
  mainSections = ["introduction"]

[[menu.main]]
  name = "Introduction"
  url = "/commentary/introduction/"
  weight = 1

[[menu.main]]
  name = "Commentary"
  url = "/commentary/chapters/"
  weight = 2

